version: '3'
services:
  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=green_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"

  api:
    build: .
    command: ["./entrypoint.sh", "db"]
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@api.com
    - PGADMIN_DEFAULT_PASSWORD=admin123
    - PGADMIN_LISTEN_PORT=80
    - PGADMIN_DEFAULT_SERVER=db
    - POSTGRES_PASSWORD=123
    - POSTGRES_USER=postgres
    - POSTGRES_DB=green_api
    - POSTGRES_HOST=db
    - POSTGRES_PORT=5432
    ports:
      - "5050:80"
    depends_on:
      - db
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api