# Generated by Django 4.2.3 on 2023-07-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0005_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_footprint', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='service',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='services',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
        migrations.AddField(
            model_name='climateimpact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.users'),
        ),
    ]
